texto = input('Digite algo: ')
print('O tipo primitivo desse testo é',type(texto))
print('Só tem espaços? : ',texto.isspace())
print('É um número? : ',texto.isnumeric())
print('É alfabético? : ',texto.isalpha())
print('É alfanumérico? :',texto.isalnum())
print('Esta em maiusculas? : ',texto.isupper())
print('Esta em minusculas? : ',texto.islower())
print('Esta capitalizada? : ',texto.istitle())