d = int(input('Por quantos dias o carro foi alugado: '))
km = float(input('Quantos km foram percorridos: '))
v = (d*60) + (km*0.15)
print('='*40)
print('O valor a ser pago é: R$ {:.2f}'.format(v))
print('='*40)