t = int(input('Digite a quantidade de termos da sequência de FIBONACCI deseja ver: '))
t1 = 0
t2 = 1
print(f'{t1} -> {t2}', end='')
c = 3
while c <= t:
    t3 = t1 + t2
    print(f' -> {t3}', end='')
    c += 1
    t1 = t2
    t2 = t3
